FROM mcr.microsoft.com/dotnet/sdk:6.0-focal

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip procps \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

RUN groupadd --gid 1000 dotnet \
    && useradd -s /bin/bash --uid 1000 --gid 1000 -m dotnet
RUN mkdir /app && chown dotnet:dotnet /app
USER dotnet

ENV PATH="$PATH:/home/dotnet/.dotnet/tools"
RUN dotnet tool install -g dotnet-ef --version '6.0.0-*'

ARG APP_VERSION

ENV ASPNETCORE_URLS=http://*:8080
ENV ASPNETCORE_ENVIRONMENT=Development
ENV APP_VERSION=${APP_VERSION}
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
EXPOSE 8080

WORKDIR /app
COPY Docker.Directory.Build.props Directory.Build.props

WORKDIR /app/code/src/Apps/FoodReview.Api
SHELL ["/bin/bash", "-c"]
ENTRYPOINT dotnet restore && \
    dotnet watch run --no-restore
